# Generated by Django 5.1.2 on 2024-10-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_stockdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='symbol',
            field=models.CharField(default='AAPL', max_length=11),
            preserve_default=False,
        ),
    ]
