# Generated by Django 5.1.2 on 2024-10-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stockdata_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('investment', models.IntegerField()),
                ('buy_range', models.IntegerField()),
                ('sell_range', models.IntegerField()),
                ('sharpe', models.FloatField()),
                ('sortino', models.FloatField()),
                ('VaR', models.FloatField()),
                ('max_drawdown', models.FloatField()),
                ('total_return', models.FloatField()),
                ('trade_count', models.FloatField()),
            ],
        ),
    ]
