# Generated by Django 5.1.2 on 2024-10-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_backtestresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresults',
            name='report_filepath',
            field=models.CharField(default='api/static/pdf/model_performance_AAPL_2024-10-19.pdf', max_length=200),
            preserve_default=False,
        ),
    ]
