name: Deploy blockhouse

on:
  push:
    branches:
    - 'cdtest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install gcloud cli
      uses: google-github-actions/setup-gcloud
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    
    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-docker.pkg.dev
        docker build -t us-docker.pkg.dev/$GOOGLE_PROJECT/blockhouse-service:latest .
        docker push us-docker.pkg.dev/$GOOGLE_PROJECT/blockhouse-service:latest

    - name: Deploy to Cloud Run
        run:  |
          gcloud run deploy chain-service --image us-docker.pkg.dev/$GOOGLE_PROJECT/blockhouse-service:latest  \
            --platform managed --region us-central1 --concurrency 1 \
            --min-instances 1 --max-instances 1